# --- !Ups

CREATE TABLE "NEOLOGISM" ("ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "QUOTATION" VARCHAR NOT NULL, "ATTRIBUTION" VARCHAR NOT NULL, "TIME" TIMESTAMP, "EXPLANATION" VARCHAR, "RARITY" INT, "TONITRUS" FLOAT);
CREATE TABLE "CAT" ("NAME" VARCHAR NOT NULL PRIMARY KEY,"COLOR" VARCHAR NOT NULL, "CUTENESS" INT);
create TABLE "DOG" ("NAME" VARCHAR NOT NULL PRIMARY KEY,"COLOR" VARCHAR NOT NULL);

# --- !Downs

DROP TABLE "NEOLOGISM";
DROP TABLE "CAT";
DROP TABLE "DOG";
